// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLbBwjj0ogfr5n9Ni4uZuA4uTv57U8aeE',
    appId: '1:620922972085:web:a4d0fa53eb6a247fb41bfc',
    messagingSenderId: '620922972085',
    projectId: 'quiz-app-a706f',
    authDomain: 'quiz-app-a706f.firebaseapp.com',
    storageBucket: 'quiz-app-a706f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbbDGi-U2WRnqHw8n25ZiG7Ydfa5xxYWU',
    appId: '1:620922972085:android:5244269cf7f70b35b41bfc',
    messagingSenderId: '620922972085',
    projectId: 'quiz-app-a706f',
    storageBucket: 'quiz-app-a706f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV-2AfIZbY6yAs0s_utkG1_TzxigjvZT0',
    appId: '1:620922972085:ios:394356fa1db32fa4b41bfc',
    messagingSenderId: '620922972085',
    projectId: 'quiz-app-a706f',
    storageBucket: 'quiz-app-a706f.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV-2AfIZbY6yAs0s_utkG1_TzxigjvZT0',
    appId: '1:620922972085:ios:394356fa1db32fa4b41bfc',
    messagingSenderId: '620922972085',
    projectId: 'quiz-app-a706f',
    storageBucket: 'quiz-app-a706f.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLbBwjj0ogfr5n9Ni4uZuA4uTv57U8aeE',
    appId: '1:620922972085:web:953974e6fde3363db41bfc',
    messagingSenderId: '620922972085',
    projectId: 'quiz-app-a706f',
    authDomain: 'quiz-app-a706f.firebaseapp.com',
    storageBucket: 'quiz-app-a706f.firebasestorage.app',
  );
}
